create index.html
ok-technopolis-autumn-2019/Kirill_Kungurov pull request #1
Opened 2019-10-09 09:12 UTC by KirKungurov

2019-10-11 10:07 UTC, fromanywhere requested changes

2019-10-11 10:07 UTC, fromanywhere commented on index.html
> +	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
Здесь есть лишние атрибуты, посмотрите на  <meta charset

2019-10-11 10:07 UTC, fromanywhere commented on index.html
> +				<input type="image"
input type="image" здесь не очень хорошо. Картинку будем класть стилями

2019-10-11 10:07 UTC, fromanywhere commented on index.html
> +				<message class="todos-panel-actions-message">3 items left</message>
если кастомный тег, то у него должен быть дефис по спецификации в названии

2019-10-11 10:07 UTC, fromanywhere commented on index.html
> +				<li class="todos-table-footer-list-w">
li просто так не вкладывается, нужна группировка в список

2019-10-15 08:25 UTC, fromanywhere commented on index.html
> +				<message class="todos-panel-actions-message">3 items left</message>
Всё еще не матчится с требованиями спецификации по кастомным тегам. В общем, поставить div видимо будет проще

2019-10-15 09:12 UTC, KirKungurov commented on index.html
> +				<message class="todos-panel-actions-message">3 items left</message>
Пофиксил

> Всё еще не матчится с требованиями спецификации по кастомным тегам. В общем, поставить div видимо будет проще

пофиксил

2019-10-15 10:20 UTC, fromanywhere approved these changes

2019-10-15 10:31 UTC, merged