Make css great again
ok-technopolis-autumn-2019/Kirill_Kungurov pull request #2
Opened 2019-10-26 16:27 UTC by KirKungurov

Добрый вечер, два вопрос:
Как сделать так, что бы при фокусе на уже активированный чекбокс не менялся цвет границ круга?
Как сделать так, чтобы была доступна возможно "Ходить" табами?

2019-10-26 20:02 UTC, fromanywhere requested changes

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	background: #ffffff;
шрифт бы прямо сюда прописать

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	letter-spacing: -2.5px;
не надо этого

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +.todos-table__list__task{
нейминг не по бэму, не может быть элементов элементов https://habr.com/post/305548/

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	border: 1px solid #5dc2af;
еще бы подсветить .todos-table-list-task__checkbox:focus +
.todos-table-list-task__check

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	opacity: 1;
здесь не хватает todos-table-list-task__button:focus { opacity: 1; }

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	border: 2px solid #EBDFDF;
фильтры прыгают по горизонтали при выборе. Попробуйте нарисовать им прозрачную границу такой же ширины в состоянии по умолчанию

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	color: #666666;
Прилипает к границам, когда много текста 
![image](https://user-images.githubusercontent.com/1042969/67625262-72dc1000-f844-11e9-92bd-1bfc7047bb62.png)

2019-10-26 20:02 UTC, fromanywhere commented on style.css
> +	align-items: center;
теней не хватает по макету

2019-10-26 20:02 UTC, fromanywhere commented on index.html
> +						class="todos-table-actions__clearAll-button"
не может быть кемелкейса по бэму

2019-10-26 20:03 UTC, fromanywhere commented
> Добрый вечер, два вопрос:
> Как сделать так, что бы при фокусе на уже активированный чекбокс не менялся цвет границ круга?
> Как сделать так, чтобы была доступна возможно "Ходить" табами?

ну, в целом оно уже и сейчас ходит, только нужно не забывать это посвечивать, я там указал пару мест. 

что касается фокуса на уже активированный чекбокс, у меня вроде не меняется, но в любом случае это вопрос веса селекторов — кто кого будет перевешивать

2019-10-26 20:41 UTC, KirKungurov commented on style.css
> +	background: #ffffff;
add

2019-10-26 20:45 UTC, KirKungurov commented on style.css
> +	border: 2px solid #EBDFDF;
А если специально сделал, чтобы как бы элемент выпрыгивал на пользователя?

2019-10-26 20:52 UTC, KirKungurov commented on style.css
> +	color: #666666;
Добавил padding

2019-10-26 20:54 UTC, KirKungurov commented on index.html
> +						class="todos-table-actions__clearAll-button"
fix

2019-10-26 20:59 UTC, KirKungurov commented on style.css
> +	letter-spacing: -2.5px;
fix

2019-10-26 21:02 UTC, KirKungurov commented on style.css
> +	border: 1px solid #5dc2af;
Вместо focus поставил hover, иначе не срабатывало. Появился баг
>>Как сделать так, что бы при фокусе на уже активированный чекбокс не менялся цвет границ круга?

2019-10-26 21:04 UTC, fromanywhere commented on style.css
> +	border: 2px solid #EBDFDF;
Тогда я бы добавил transition, чтобы оно не било по глазам, и убедился бы в консистентности спецэффектов и на фокусе тоже

2019-10-26 21:07 UTC, KirKungurov commented on style.css
> +	opacity: 1;
add

2019-10-26 21:07 UTC, fromanywhere commented on style.css
> +	border: 1px solid #5dc2af;
можно же перекрасить обратно. Что-нибудь в духе .todos-table-list-task__checkbox:checked:focus + .todos-table-list-task__check

2019-10-26 21:17 UTC, KirKungurov commented on style.css
> +	border: 1px solid #5dc2af;
Помогло

2019-10-26 21:20 UTC, KirKungurov commented on style.css
> +.todos-table__list__task{
fix

2019-10-26 21:21 UTC, KirKungurov commented on style.css
> +	border: 1px solid #5dc2af;
add

2019-10-26 21:41 UTC, KirKungurov commented on style.css
> +	align-items: center;
add

2019-10-29 19:55 UTC, fromanywhere approved these changes
Аппрув авансом

2019-10-29 19:55 UTC, fromanywhere commented on style.css
> +.todos-table__task:focus .todos-table-list-task__button,
Так не работает же клавиатурный фокус так. А почему? Потому что .todos-table-list-task__button:focus

2019-10-29 19:55 UTC, fromanywhere commented on style.css
> +	border: 1px solid #CCCCCC;
и на фокус бы так же

2019-10-29 22:26 UTC, merged